force-app/main/default/objects/Opportunity/fields/destination__c.field-meta.xml
<CustomField>
    <fullName>destination__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/numberOfParticipants__c.field-meta.xml
<CustomField>
    <fullName>numberOfParticipants__c</fullName>
    <label>numberOfParticipants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>startDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/totalCost__c.field-meta.xml
<CustomField>
    <fullName>totalCost__c</fullName>
    <label>totalCost</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Trip</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip</relationshipLabel>
    <relationshipName>Trip</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/destination__c.field-meta.xml
<CustomField>
    <fullName>destination__c</fullName>
    <label>destination</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>endDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/numberOfParticipants__c.field-meta.xml
<CustomField>
    <fullName>numberOfParticipants__c</fullName>
    <label>numberOfParticipants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trip</relationshipLabel>
    <relationshipName>Trip</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>A venir</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/totalCost__c.field-meta.xml
<CustomField>
    <fullName>totalCost__c</fullName>
    <label>totalCost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityService.cls
public with sharing class OpportunityService {

    public class OpportunityValidationException extends Exception {
    }

    public void validateOpportunity(Set<Id> OpportunityIds) {

        // Récupérer les objets Opportunity correspondants aux IDs
        List<Opportunity> OpportunitysToProcess = OpportunitySelector.getOpportunityByIds(OpportunityIds);
        for (Opportunity opp : OpportunitysToProcess) {
            System.debug('opp.StageName==' +opp.StageName);
                if(opp.StageName=='Closed Won')
                    {
                        try {
                            Trip__c newTrip = new Trip__c(
                                Account__c =opp.accountid ,
                               destination__c =opp.destination__c ,
                                endDate__c =opp.endDate__c ,
                                numberOfParticipants__c =opp.numberOfParticipants__c ,
                               Opportunity__c =opp.Id   ,
                                startDate__c=opp.startDate__c  ,
                                status__c='A venir' ,
                                totalCost__c=opp.totalCost__c  
                              );
                              insert newTrip;
                              System.debug('Insertion dans newTrip ok');

                        } catch (Exception ex) {
                             System.debug('Erreur insert ...' + ex.getMessage());
                             throw new OpportunityValidationException('Les dates ne sont pas dans le bon ordre!!!'   );
                        }

                    }


        }


        }

}