force-app/main/default/objects/Opportunity/fields/destination__c.field-meta.xml
<CustomField>
    <fullName>destination__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/numberOfParticipants__c.field-meta.xml
<CustomField>
    <fullName>numberOfParticipants__c</fullName>
    <label>numberOfParticipants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>startDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/totalCost__c.field-meta.xml
<CustomField>
    <fullName>totalCost__c</fullName>
    <label>totalCost</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/OpportunitySelector.cls
public with sharing class OpportunitySelector {
    public static List<Opportunity> getOpportunityByIds(Set<Id> OpportunityIds) {
        List<Opportunity> OpportunityToProcess = [SELECT Id FROM Opportunity WHERE Id IN :OpportunityIds  WITH SECURITY_ENFORCED]; //conversion en list Opportunity
        List<Opportunity> Opportunitys = [   SELECT Id, StageName, AccountId ,destination__c,endDate__c,startDate__c,numberOfParticipants__c,totalCost__c FROM Opportunity   WHERE Id IN :OpportunityToProcess   WITH SECURITY_ENFORCED   ];
        return Opportunitys;
      }
}