force-app/main/default/objects/Opportunity/fields/destination__c.field-meta.xml
<CustomField>
    <fullName>destination__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/numberOfParticipants__c.field-meta.xml
<CustomField>
    <fullName>numberOfParticipants__c</fullName>
    <label>numberOfParticipants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>startDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Trip</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/destination__c.field-meta.xml
<CustomField>
    <fullName>destination__c</fullName>
    <label>destination</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>endDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/numberOfParticipants__c.field-meta.xml
<CustomField>
    <fullName>numberOfParticipants__c</fullName>
    <label>numberOfParticipants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trip</relationshipLabel>
    <relationshipName>Trip</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>A venir</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripServiceTest.cls
@IsTest
private class TripServiceTest {
    @TestSetup
    static void setup() {
      TestDataFactory.createTestexecuteTripCancel();
        TestDataFactory.createTestTripServiceUpdate();
        TestDataFactory.createTestvalidateTripOnOpportunity();
        TestDataFactory.createTestexecuteTripUpdateCase1();
        TestDataFactory.createTestexecuteTripUpdateCase2();
        TestDataFactory.createTestexecuteTripUpdateCase3();
    }


    @IsTest
    static void testexecuteTripUpdate(){
      Test.startTest();
      List<Trip__c> trips=[select id, name,numberOfParticipants__c,Status__c,startDate__c,endDate__c from trip__c where status__c='Terminé'  and destination__c='testupdate' ];
      TripService.executeTripUpdate(trips);
      List<Trip__c> results=[select id, name,Status__c from trip__c ];        
     
      
      List<Trip__c> results1=[select id, name,Status__c,destination__c from trip__c where Status__c='A venir'  and destination__c='testupdate' ];     
      System.assertEquals(1, results1.size(), 'La liste result doit contenir 1 ligne.');

      List<Trip__c>  results2=[select id, name,Status__c,destination__c from trip__c where Status__c='En cours'  and destination__c='testupdate' ];     
      System.assertEquals(1, results2.size(), 'La liste result doit contenir 1 ligne.');

      List<Trip__c>  results3=[select id, name,Status__c,destination__c from trip__c where Status__c='Terminé'  and destination__c='testupdate' ];     
      System.assertEquals(1, results3.size(), 'La liste result doit contenir 1 ligne.');
      Test.stopTest();

    }

    @IsTest
    static void testexecuteTripCanceled() {

      Test.startTest();
      List<Trip__c> trips=[select id, name,numberOfParticipants__c from trip__c where status__c='A venir'  ];
      TripService.executeTripCanceled(trips);

      List<Trip__c> results=[select id, name from trip__c where status__c='Annulé'  ];
      Test.stopTest();
      System.assertNotEquals(3, results.size(),'La liste doit avoir 3 elements' );

    }


    @IsTest
  static void testvalidateTripInsert() {
    Test.startTest();
    List<Trip__c> trips = new List<Trip__c>();  
    Trip__c   trip=  new Trip__c(
         startDate__c = Date.today().addDays(5),  // Trip à venir
         endDate__c=Date.today().addDays(10),
            numberOfParticipants__c =7, // Un trip à annuler (moins de 10 participants)
            Status__c = 'A venir'
        );  
    insert trip;
    Test.stopTest();

    Trip__c results=[select id, name from trip__c where id=:trip.id  ];
    System.assertNotEquals(null, results,'La liste des résultats ne doit pas être nulle' );

  }


  @IsTest
  static void testvalidateTripUpdate() {
        Test.startTest();
        List<Trip__c> trips = [SELECT Id, Name, Status__c FROM Trip__c];
        for (Trip__c trip : trips) {
            trip.Status__c = 'Annulé';
        }    
        update trips;
    Test.stopTest();

    List<Trip__c> results=[select id, name from trip__c where Status__c='Annulé'];
    System.assert(results.size() > 0, 'La liste des résultats doit contenir au moins un élément.');
  }

  @IsTest
  static void testvalidateTripServiceOpportunity() {
    Opportunity opp=[select id, name from Opportunity where destination__c = 'testOppCloseWon'];
    Test.startTest();
    opp.StageName='Closed Won';
    update opp;
    Test.stopTest();

    List<Trip__c> results=[select id from trip__c where  Opportunity__c=:opp.id ];
    System.assertNotEquals(null, results,'La liste des résultats ne doit pas être nulle' );
  }
}