force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Trip</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>endDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/numberOfParticipants__c.field-meta.xml
<CustomField>
    <fullName>numberOfParticipants__c</fullName>
    <label>numberOfParticipants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>A venir</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripSelector.cls
public class TripSelector {
    
    // Méthode pour récupérer les voyages à venir dans les 7 prochains jours
    public static Database.QueryLocator getUpcomingTrips() {
        return Database.getQueryLocator('SELECT Id, Status__c, startDate__c, numberOfParticipants__c FROM Trip__c WHERE (numberOfParticipants__c < 10) and (startDate__c >= TODAY AND startDate__c <= NEXT_N_DAYS:7 ) WITH SECURITY_ENFORCED');
    }


       // Méthode pour récupérer tous les voyages
       public static Database.QueryLocator getAllTrips() {
        return Database.getQueryLocator('SELECT Id, Status__c, startDate__c, numberOfParticipants__c,endDate__c FROM Trip__c   WITH SECURITY_ENFORCED');
    }
}