force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Trip</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>A venir</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripCanceledBatchJobTest.cls
@IsTest
private class TripCanceledBatchJobTest {
    @TestSetup
    static void setup() {
        TestDataFactory.createTestTripCanceledBatchJob();
    }


    @IsTest
    static void TripCanceledBatchJob() {
       
        Test.startTest();
        TripCanceledBatchJob batch = new TripCanceledBatchJob();
        Database.executeBatch(batch);
        Test.stopTest();

        Trip__c  trip = [SELECT Id,Status__c FROM Trip__c where Name = 'Trip Test' ];
        System.assertEquals('Annulé', trip.Status__c, 'Le trip doit être annulé.');
    }


}