force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nom de Trip</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>endDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TripService.cls
public with sharing class TripService {

    public class TripValidationException extends Exception {
    }

    public void validateTrip(List<Trip__c> TripIds) {

        for (Trip__c trip : TripIds) {
            System.debug( 'Dans la boucle For....' );
            // Vérification pour l'événement Insert
            if (Trigger.isInsert) {
                System.debug( 'isInsert trip.startDate__c==' +trip.startDate__c );                    
                System.debug( 'isInsert trip.endDate__c==' +trip.endDate__c );    
                     // Vérifier que la date de fin est après la date de début
                            if ((trip.endDate__c != null && trip.startDate__c != null) && trip.endDate__c < trip.startDate__c ) {
                                trip.addError('Cas  insert....La date de fin doit être après la date de début.');
                                //throw new TripValidationException('Chronologie incorrect!!!!'  );
                            }
            }
            if (Trigger.isUpdate) {
                System.debug( 'isUpdate trip.startDate__c==' +trip.startDate__c );                    
                System.debug( 'isUpdate trip.endDate__c==' +trip.endDate__c );  
    
                // Vérifier que la date de fin est après la date de début
                if ((trip.endDate__c != null && trip.startDate__c != null) && trip.endDate__c < trip.startDate__c ) {
                   trip.addError('Cas  insert....La date de fin doit être après la date de début.');
                     //throw new TripValidationException('Chronologie incorrect!!!!'  );
                }
               
            }
        }
    }
}